name: Issue or bug
description: Describe your problem in detail 
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in jugaad-data! 🚀

        I'm creating a simple checklist and a form to collect details  about the issue/bug you are facing.

        This is required to avoid back and forth conversation and time delay to collect most basic information without which its very difficult to replicate the issue and hence difficult to resolve.

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        What is the problem, question, or error?

        Write a short description telling me what you are doing, what you expect to happen, and what is currently happening.
      placeholder: Expected behaviour and what actually happened
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true
   - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        If I (or someone) can copy it, run it, and see it right away, there's a much higher chance I (or someone) will be able to help you.

      placeholder: |
                from datetime import date
                from jugaad_data.nse import bhavcopy_save, bhavcopy_fo_save

                # Download bhavcopy
                bhavcopy_save(date(2020,1,1), "/path/to/directory")

                # Download bhavcopy for futures and options
                bhavcopy_fo_save(date(2020,1,1), "/path/to/directory")

                # Download stock data to pandas dataframe
                from jugaad_data.nse import stock_df
                df = stock_df(symbol="SBIN", from_date=date(2020,1,1),
                            to_date=date(2020,1,30), series="EQ")
      render: python
    validations:
      required: true

 - type: textarea
    id: error
    attributes:
      label: Error snippet
      description: |
              Please share the error description
      placeholder: |
              "Exception: xyz"
     render: python
    validations:
      required: true
   - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I added the relevant code snippet which crashed or which has an issue
          required: true
        - label: I added the relevant error snippet 
          required: true
